#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

https://projecteuler.net/problem=2
"""

from utils import fibonacci_numbers


def solve():
    result = 0
    max_fib = 4000000

    for fib in fibonacci_numbers():
        if fib > max_fib:
            break
        elif fib % 2 == 0:
            result += fib

    return result

if __name__ == '__main__':
    print solve()
